#!/usr/bin/python3
# -*- coding: utf-8 -*-

# Copyright © 2013-2014 Martin Ueding <dev@martin-ueding.de>

"""
Downloads the notes in the JSON format and inserts them in the taskwarrior
database.
"""

import argparse
import configparser
import json
import os
import os.path
import requests
import subprocess

__docformat__ = "restructuredtext en"

configfile = os.path.expanduser("~/.config/php-note-capture/config.ini")
notesfile = "notes.js"

def main():
    options = _parse_args()

    config = configparser.ConfigParser()
    config.read(configfile)

    realm = config.get("auth", "realm")
    uri = config.get("auth", "uri")
    user = config.get("auth", "user")
    passwd = config.get("auth", "passwd")
    cert = os.path.expanduser(config.get("auth", "cert"))
    reseturl = config.get("reset", "reseturl")

    if os.path.isfile(notesfile):
        os.remove(notesfile)

    r = requests.get(uri, auth=(user, passwd), verify=cert)
    if r.status_code != 200:
        print(r.status_code)

    notes = r.json()

    try:
        if len(notes) > 0:
            for note in notes:
                text = note["text"]
                command = ["task", "add", text]
                if "priority" in note:
                    priority = note["priority"]
                    if priority.lower() in ["l", "h", "m"]:
                        command += ["pri:{}".format(priority)]

                if "entry" in note:
                    entry = note["entry"]
                    command += ["entry:{}".format(entry)]

                subprocess.check_call(command)
                print("Note “{}” created.".format(text))

            r = requests.get(reseturl, auth=(user, passwd), verify=cert)
        else:
            print("No new notes. Done.")
    except subprocess.CalledProcessError as e:
        raise


def _parse_args():
    """
    Parses the command line arguments.

    :return: Namespace with arguments.
    :rtype: Namespace
    """
    parser = argparse.ArgumentParser(description="")
    #parser.add_argument("args", metavar="N", type=str, nargs="*", help="Positional arguments.")
    #parser.add_argument("", dest="", type="", default=, help=)
    #parser.add_argument("--version", action="version", version="<the version>")

    return parser.parse_args()


if __name__ == "__main__":
    main()
